# -*- coding: utf-8 -*-
"""Assignment1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2TG7chNNaRDiH0XCym0TYLQooAF80NQ
"""

from sympy import *
from math import *
r=float(input("Input the radius of the radius:"))
a= pi*r*r
print("The Area of the circle is given by:",a)

from sympy import *
fname= input("Input the Filename:")
fext=filename.split(".")
print ("The extension of the file is : " + repr(fext[-1]))