# -*- coding: utf-8 -*-
"""Fibonacci.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17xuEQbGd_U7zDrgqNjkeIefNZHwc6PxS
"""

from sympy import *
n=int(input("Enter the number of terms:"))
n1=0
n2=1
count=0
if n<=0:
  print("Enter a positive integer:")
elif n==1:
  print("Fibonacci sequence upto",n,"terms is:")
  print(n1)
else:
  print("Fibonacci sequence:")
  while count < n:
    print(n1)
    nth=n1+n2
    n1=n2
    n2=nth
    count=count+1