# -*- coding: utf-8 -*-
"""Positive.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ql_nUK7Y9E51VjgUrrDnl1sCP5gSCf2y
"""

from sympy import*
list1=[12, -7, 5, 64, -14]
num=0
while (num < len(list1)):
  if list1[num] >=0 :
    print(list1[num], end = " ")
    num = num+1

from sympy import*
list1=[12, 14, -95, 3]
num=0
while (num < len(list1)):
  if list1[num] >=0 :
    print(list1[num], end = " ")
    num = num+1